<?php
/**
 * Dynamically loads the class attempting to be instantiated elsewhere in the
 * plugin.
 *
 * @package Charitable\Includes
 */

spl_autoload_register( 'charitable_autoloader' );

/**
 * Dynamically loads the class attempting to be instantiated elsewhere in the
 * plugin by looking at the $class_name parameter being passed as an argument.
 *
 * @param string $class_name The fully-qualified name of the class to load.
 * @since   1.5.0
 * @return  bool
 */
function charitable_autoloader( $class_name ) {
 
    // If the specified $class_name already exists, bail.
    if ( class_exists( $class_name ) ) {
        return;
    }

    // If the specified $class_name does not include our namespace, duck out.
    if ( false === strpos( $class_name, 'Charitable_' ) ) {
        return;
    }

    // Autogenerated class map.
    include( 'charitable-class-map.php' );
    // End class map.

    static $includes_path = charitable()->get_path( 'includes' );

    $file_path = isset( $mapping[$class_name] ) ? trailingslashit( $includes_path ) . $mapping[$class_name] : false;

    if ( $file_path && file_exists( $file_path ) && is_file( $file_path ) ) {
        require_once( $file_path );
        return true;
    }

    return false;
}


